name: Build & Deploy (Production)

on:
  push:
    branches:
      - main
    paths:
      - 'packages/server/**'
      # os pacotes que dependem uns dos outros
      # tb precisam fazer parrte do pipe


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Deploy
        run: echo "Deployed"
